#include"xiong.h"


void open_file(char* file_name) {
	char path[_MAX_PATH];
	get_file_path(path, sizeof(path));

	char tempPath[_MAX_PATH];
	snprintf(tempPath, sizeof(tempPath), "\"%s\\%s\"", path, file_name);
	strncpy_s(path, sizeof(path), tempPath, _TRUNCATE);

	printf("HTML 文件已生成,保存路径:\n");
	printf("%s\n", path);

	printf("正在尝试打开%s...\n", file_name);
	run_file(path);

}


void run_file(const char* path) {
	int ret = system(path);
	if (ret == -1) {
		perror("system调用失败");
	}
	else {
		printf("退出码: %d\n", ret);
	}
}


void get_file_path(char* buffer, int size) {
	if (_getcwd(buffer, size) == NULL) {
		perror("_getcwd() error");
		exit(EXIT_FAILURE);
	}
}


void generate_info_report(cJSON* root) {

	char* str = cJSON_Print(root);

	const char* filename = "user_info.html";
	printf("正在生成HTML文件...\n");
	FILE* htmlFile = fopen(filename, "w");//新建 report.html文件
	if (htmlFile == NULL) {
		printf("文件创建失败\n");
		return;
	}

	// 写入HTML文件内容
	// 用户信息
	{
		fprintf(htmlFile, "<!DOCTYPE html>\n");
		fprintf(htmlFile, "<html lang=\"en\">\n");
		fprintf(htmlFile, "<head>\n");
		fprintf(htmlFile, "    <meta charset=\"UTF-8\">\n");
		fprintf(htmlFile, "    <meta name= \" viewport \" content= \"width=device-width, initial-scale=1.0 \" >\n");
		fprintf(htmlFile, "    <title>Codeforces User Profile</title>\n");
		fprintf(htmlFile, "    <style>\n");
		fprintf(htmlFile, "        body {\n");
		fprintf(htmlFile, "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
		fprintf(htmlFile, "            background-color: #f5f5f5;\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            color: #333;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .container {\n");
		fprintf(htmlFile, "            max-width: 800px;\n");
		fprintf(htmlFile, "            margin: 0 auto;\n");
		fprintf(htmlFile, "            background-color: white;\n");
		fprintf(htmlFile, "            border-radius: 10px;\n");
		fprintf(htmlFile, "            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\n");
		fprintf(htmlFile, "            overflow: hidden;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .header {\n");
		fprintf(htmlFile, "            background-color: #3b5998;\n");
		fprintf(htmlFile, "            color: white;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .profile {\n");
		fprintf(htmlFile, "            display: flex;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            border-bottom: 1px solid #eee;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .avatar {\n");
		fprintf(htmlFile, "            width: 150px;\n");
		fprintf(htmlFile, "            height: 150px;\n");
		fprintf(htmlFile, "            border-radius: 50%%;\n");
		fprintf(htmlFile, "            object-fit: cover;\n");
		fprintf(htmlFile, "            border: 5px solid #f5f5f5;\n");
		fprintf(htmlFile, "            margin-right: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .profile-info {\n");
		fprintf(htmlFile, "            flex: 1;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .name {\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "            margin: 0 0 5px 0;\n");
		fprintf(htmlFile, "            color: #3b5998;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .rank {\n");
		fprintf(htmlFile, "            font-size: 18px;\n");
		fprintf(htmlFile, "            margin: 0 0 10px 0;\n");
		fprintf(htmlFile, "            color: #ff5722;\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .details {\n");
		fprintf(htmlFile, "            display: grid;\n");
		fprintf(htmlFile, "            grid-template-columns: 1fr 1fr;\n");
		fprintf(htmlFile, "            gap: 10px;\n");
		fprintf(htmlFile, "            margin-top: 15px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .detail-item {\n");
		fprintf(htmlFile, "            margin-bottom: 8px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .detail-label {\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            color: #666;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .stats {\n");
		fprintf(htmlFile, "            display: flex;\n");
		fprintf(htmlFile, "            justify-content: space-around;\n");
		fprintf(htmlFile, "            padding: 15px;\n");
		fprintf(htmlFile, "            background-color: #f9f9f9;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .stat-item {\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .stat-value {\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            color: #3b5998;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .stat-label {\n");
		fprintf(htmlFile, "            font-size: 14px;\n");
		fprintf(htmlFile, "            color: #666;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .title-photo {\n");
		fprintf(htmlFile, "            width: 100%%;\n");
		fprintf(htmlFile, "            height: 200px;\n");
		fprintf(htmlFile, "            object-fit: cover;\n");
		fprintf(htmlFile, "            border-bottom: 1px solid #eee;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .timestamp {\n");
		fprintf(htmlFile, "            color: #888;\n");
		fprintf(htmlFile, "            font-size: 12px;\n");
		fprintf(htmlFile, "            text-align: right;\n");
		fprintf(htmlFile, "            padding: 10px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </style>\n");
		fprintf(htmlFile, "</head>\n");
		fprintf(htmlFile, "<body>\n");
		fprintf(htmlFile, "    <div class=\"container\">\n");
		fprintf(htmlFile, "        <div class=\"header\">\n");
		fprintf(htmlFile, "            <h1>Codeforces User Profile</h1>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "        \n");
		fprintf(htmlFile, "        <img id=\"titlePhoto\" class=\"title-photo\" src=\"\" alt=\"Title Photo\">\n");
		fprintf(htmlFile, "        \n");
		fprintf(htmlFile, "        <div class=\"profile\">\n");
		fprintf(htmlFile, "            <img id=\"avatar\" class=\"avatar\" src=\"\" alt=\"Profile Picture\">\n");
		fprintf(htmlFile, "            <div class=\"profile-info\">\n");
		fprintf(htmlFile, "                <h2 id=\"name\" class=\"name\"></h2>\n");
		fprintf(htmlFile, "                <p id=\"rank\" class=\"rank\"></p>\n");
		fprintf(htmlFile, "                \n");
		fprintf(htmlFile, "                <div class=\"details\">\n");
		fprintf(htmlFile, "                    <div class=\"detail-item\">\n");
		fprintf(htmlFile, "                        <span class=\"detail-label\">Handle:</span>\n");
		fprintf(htmlFile, "                        <span id=\"handle\"></span>\n");
		fprintf(htmlFile, "                    </div>\n");
		fprintf(htmlFile, "                    <div class=\"detail-item\">\n");
		fprintf(htmlFile, "                        <span class=\"detail-label\">Organization:</span>\n");
		fprintf(htmlFile, "                        <span id=\"organization\"></span>\n");
		fprintf(htmlFile, "                    </div>\n");
		fprintf(htmlFile, "                    <div class=\"detail-item\">\n");
		fprintf(htmlFile, "                        <span class=\"detail-label\">Location:</span>\n");
		fprintf(htmlFile, "                        <span id=\"location\"></span>\n");
		fprintf(htmlFile, "                    </div>\n");
		fprintf(htmlFile, "                    <div class=\"detail-item\">\n");
		fprintf(htmlFile, "                        <span class=\"detail-label\">Contribution:</span>\n");
		fprintf(htmlFile, "                        <span id=\"contribution\"></span>\n");
		fprintf(htmlFile, "                    </div>\n");
		fprintf(htmlFile, "                    <div class=\"detail-item\">\n");
		fprintf(htmlFile, "                        <span class=\"detail-label\">Registered:</span>\n");
		fprintf(htmlFile, "                        <span id=\"registration\"></span>\n");
		fprintf(htmlFile, "                    </div>\n");
		fprintf(htmlFile, "                    <div class=\"detail-item\">\n");
		fprintf(htmlFile, "                        <span class=\"detail-label\">Last Online:</span>\n");
		fprintf(htmlFile, "                        <span id=\"lastOnline\"></span>\n");
		fprintf(htmlFile, "                    </div>\n");
		fprintf(htmlFile, "                </div>\n");
		fprintf(htmlFile, "            </div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "        \n");
		fprintf(htmlFile, "        <div class=\"stats\">\n");
		fprintf(htmlFile, "            <div class=\"stat-item\">\n");
		fprintf(htmlFile, "                <div class=\"stat-value\" id=\"rating\"></div>\n");
		fprintf(htmlFile, "                <div class=\"stat-label\">Current Rating</div>\n");
		fprintf(htmlFile, "            </div>\n");
		fprintf(htmlFile, "            <div class=\"stat-item\">\n");
		fprintf(htmlFile, "                <div class=\"stat-value\" id=\"maxRating\"></div>\n");
		fprintf(htmlFile, "                <div class=\"stat-label\">Max Rating</div>\n");
		fprintf(htmlFile, "            </div>\n");
		fprintf(htmlFile, "            <div class=\"stat-item\">\n");
		fprintf(htmlFile, "                <div class=\"stat-value\" id=\"friends\"></div>\n");
		fprintf(htmlFile, "                <div class=\"stat-label\">Friends</div>\n");
		fprintf(htmlFile, "            </div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "        \n");
		fprintf(htmlFile, "        <div class=\"timestamp\">\n");
		fprintf(htmlFile, "            Data fetched: <span id=\"fetchTime\"></span>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "    </div>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "    <script>\n");
		fprintf(htmlFile, "        // JSON data\n");
		fprintf(htmlFile, "        const jsonData = %s;", str);//json数据导入
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Format timestamp to readable date\n");
		fprintf(htmlFile, "        function formatTimestamp(timestamp) {\n");
		fprintf(htmlFile, "            const date = new Date(timestamp * 1000);\n");
		fprintf(htmlFile, "            return date.toLocaleString();\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Capitalize first letter of each word\n");
		fprintf(htmlFile, "        function capitalize(str) {\n");
		fprintf(htmlFile, "            return str.replace(/\\b\\w/g, l => l.toUpperCase());\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Populate the HTML with data\n");
		fprintf(htmlFile, "        function populateData() {\n");
		fprintf(htmlFile, "            const user = jsonData.result[0];\n");
		fprintf(htmlFile, "            \n");
		fprintf(htmlFile, "            // Set images\n");
		fprintf(htmlFile, "            document.getElementById('titlePhoto').src = user.titlePhoto;\n");
		fprintf(htmlFile, "            document.getElementById('avatar').src = user.avatar;\n");
		fprintf(htmlFile, "            \n");
		fprintf(htmlFile, "            // Set name and rank\n");
		fprintf(htmlFile, "            document.getElementById('name').textContent = `${user.firstName} ${user.lastName}`;\n");
		fprintf(htmlFile, "            document.getElementById('rank').textContent = capitalize(user.rank);\n");
		fprintf(htmlFile, "            \n");
		fprintf(htmlFile, "            // Set details\n");
		fprintf(htmlFile, "            document.getElementById('handle').textContent = user.handle;\n");
		fprintf(htmlFile, "            document.getElementById('organization').textContent = user.organization;\n");
		fprintf(htmlFile, "            document.getElementById('location').textContent = `${user.city}, ${user.country}`;\n");
		fprintf(htmlFile, "            document.getElementById('contribution').textContent = user.contribution;\n");
		fprintf(htmlFile, "            document.getElementById('registration').textContent = formatTimestamp(user.registrationTimeSeconds);\n");
		fprintf(htmlFile, "            document.getElementById('lastOnline').textContent = formatTimestamp(user.lastOnlineTimeSeconds);\n");
		fprintf(htmlFile, "            \n");
		fprintf(htmlFile, "            // Set stats\n");
		fprintf(htmlFile, "            document.getElementById('rating').textContent = user.rating;\n");
		fprintf(htmlFile, "            document.getElementById('maxRating').textContent = user.maxRating;\n");
		fprintf(htmlFile, "            document.getElementById('friends').textContent = user.friendOfCount.toLocaleString();\n");
		fprintf(htmlFile, "            \n");
		fprintf(htmlFile, "            // Set current time\n");
		fprintf(htmlFile, "            document.getElementById('fetchTime').textContent = new Date().toLocaleString();\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Call the function when page loads\n");
		fprintf(htmlFile, "        window.onload = populateData;\n");
		fprintf(htmlFile, "    </script>\n");
		fprintf(htmlFile, "</body>\n");
		fprintf(htmlFile, "</html>\n");
	}


	free(str);
	fclose(htmlFile);//关闭文件
	open_file(filename);
}


void generate_contest_list(cJSON* root) {

	char* str = cJSON_Print(root);
	const char* filename = "all_contest_list.html";
	printf("Generating HTML file...\n");
	FILE* htmlFile = fopen(filename, "w"); // Create report.html file
	if (htmlFile == NULL) {
		printf("Failed to create file\n");
		return;
	}



	{
		fprintf(htmlFile, "<!DOCTYPE html>\n");
		fprintf(htmlFile, "<html lang=\"en\">\n");
		fprintf(htmlFile, "<head>\n");
		fprintf(htmlFile, "    <meta charset=\"UTF-8\">\n");
		fprintf(htmlFile, "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
		fprintf(htmlFile, "    <title>Codeforces Contests</title>\n");
		fprintf(htmlFile, "    <style>\n");
		fprintf(htmlFile, "        body {\n");
		fprintf(htmlFile, "            font-family: Arial, sans-serif;\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "            background-color: #f9f9f9;\n");
		fprintf(htmlFile, "            color: #333;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header {\n");
		fprintf(htmlFile, "            background-color: #4CAF50;\n");
		fprintf(htmlFile, "            color: white;\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header h1 {\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header p {\n");
		fprintf(htmlFile, "            margin: 5px 0 0;\n");
		fprintf(htmlFile, "            font-size: 14px;\n");
		fprintf(htmlFile, "            color: #e0e0e0; \n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        main {\n");
		fprintf(htmlFile, "            max-width: 800px;\n");
		fprintf(htmlFile, "            margin: 20px auto;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            background-color: white;\n");
		fprintf(htmlFile, "            border-radius: 8px;\n");
		fprintf(htmlFile, "            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        section {\n");
		fprintf(htmlFile, "            margin-bottom: 30px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        section h2 {\n");
		fprintf(htmlFile, "            font-size: 20px;\n");
		fprintf(htmlFile, "            color: #4CAF50;\n");
		fprintf(htmlFile, "            margin-bottom: 10px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        ul {\n");
		fprintf(htmlFile, "            list-style-type: none;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        li {\n");
		fprintf(htmlFile, "            background-color: #f1f1f1;\n");
		fprintf(htmlFile, "            margin: 10px 0;\n");
		fprintf(htmlFile, "            padding: 15px;\n");
		fprintf(htmlFile, "            border-radius: 5px;\n");
		fprintf(htmlFile, "            display: flex;\n");
		fprintf(htmlFile, "            justify-content: space-between;\n");
		fprintf(htmlFile, "            align-items: center;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .contest-info {\n");
		fprintf(htmlFile, "            flex-grow: 1;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .contest-name {\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            margin-bottom: 5px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .contest-details {\n");
		fprintf(htmlFile, "            font-size: 14px;\n");
		fprintf(htmlFile, "            color: #666;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .status {\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            color: #4CAF50;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </style>\n");
		fprintf(htmlFile, "</head>\n");
		fprintf(htmlFile, "<body>\n");
		fprintf(htmlFile, "    <header>\n");
		fprintf(htmlFile, "        <h1>Codeforces Contests</h1>\n");
		fprintf(htmlFile, "        <p>Within the past year - Div contests</p>\n");
		fprintf(htmlFile, "    </header>\n");
		fprintf(htmlFile, "    <main>\n");
		fprintf(htmlFile, "        <!-- Divisions will be dynamically generated here -->\n");
		fprintf(htmlFile, "    </main>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "    <script>\n");
		fprintf(htmlFile, "        const data = %s;\n", str);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        function formatDuration(seconds) {\n");
		fprintf(htmlFile, "            const hours = Math.floor(seconds / 3600);\n");
		fprintf(htmlFile, "            const minutes = Math.floor((seconds % 3600) / 60);\n");
		fprintf(htmlFile, "            return `${hours}h ${minutes}m`;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        function formatDate(timestamp) {\n");
		fprintf(htmlFile, "            const date = new Date(timestamp * 1000);\n");
		fprintf(htmlFile, "            return date.toLocaleString();\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Function to classify contests by division\n");
		fprintf(htmlFile, "        function classifyContests(contests) {\n");
		fprintf(htmlFile, "            const divisions = {\n");
		fprintf(htmlFile, "                \"Div. 1\": [],\n");
		fprintf(htmlFile, "                \"Div. 2\": [],\n");
		fprintf(htmlFile, "                \"Div. 3\": [],\n");
		fprintf(htmlFile, "                \"Div. 4\": [],\n");
		fprintf(htmlFile, "                \"Other\": []\n");
		fprintf(htmlFile, "            };\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            contests.forEach(contest => {\n");
		fprintf(htmlFile, "                if (contest.name.includes(\"Div. 1\")) {\n");
		fprintf(htmlFile, "                    divisions[\"Div. 1\"].push(contest);\n");
		fprintf(htmlFile, "                } else if (contest.name.includes(\"Div. 2\")) {\n");
		fprintf(htmlFile, "                    divisions[\"Div. 2\"].push(contest);\n");
		fprintf(htmlFile, "                } else if (contest.name.includes(\"Div. 3\")) {\n");
		fprintf(htmlFile, "                    divisions[\"Div. 3\"].push(contest);\n");
		fprintf(htmlFile, "                } else if (contest.name.includes(\"Div. 4\")) {\n");
		fprintf(htmlFile, "                    divisions[\"Div. 4\"].push(contest);\n");
		fprintf(htmlFile, "                } else {\n");
		fprintf(htmlFile, "                    divisions[\"Other\"].push(contest);\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            });\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            return divisions;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Generate HTML for a single contest\n");
		fprintf(htmlFile, "        function generateContestHTML(contest) {\n");
		fprintf(htmlFile, "            const li = document.createElement('li');\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const infoDiv = document.createElement('div');\n");
		fprintf(htmlFile, "            infoDiv.className = 'contest-info';\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const nameSpan = document.createElement('span');\n");
		fprintf(htmlFile, "            nameSpan.className = 'contest-name';\n");
		fprintf(htmlFile, "            nameSpan.textContent = contest.name;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const detailsDiv = document.createElement('div');\n");
		fprintf(htmlFile, "            detailsDiv.className = 'contest-details';\n");
		fprintf(htmlFile, "            detailsDiv.innerHTML = `\n");
		fprintf(htmlFile, "                Type: ${contest.type}<br>\n");
		fprintf(htmlFile, "                Duration: ${formatDuration(contest.durationSeconds)}<br>\n");
		fprintf(htmlFile, "                Start Time: ${formatDate(contest.startTimeSeconds)}\n");
		fprintf(htmlFile, "            `;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            infoDiv.appendChild(nameSpan);\n");
		fprintf(htmlFile, "            infoDiv.appendChild(detailsDiv);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const statusSpan = document.createElement('span');\n");
		fprintf(htmlFile, "            statusSpan.className = 'status';\n");
		fprintf(htmlFile, "            statusSpan.textContent = contest.phase;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            li.appendChild(infoDiv);\n");
		fprintf(htmlFile, "            li.appendChild(statusSpan);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            return li;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Main logic to render classified contests\n");
		fprintf(htmlFile, "        function renderClassifiedContests() {\n");
		fprintf(htmlFile, "            const main = document.querySelector('main');\n");
		fprintf(htmlFile, "            const classifiedContests = classifyContests(data.result);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            Object.entries(classifiedContests).forEach(([division, contests]) => {\n");
		fprintf(htmlFile, "                if (contests.length === 0) return; // Skip empty divisions\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                const section = document.createElement('section');\n");
		fprintf(htmlFile, "                const heading = document.createElement('h2');\n");
		fprintf(htmlFile, "                heading.textContent = `${division} Contests`;\n");
		fprintf(htmlFile, "                section.appendChild(heading);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                const ul = document.createElement('ul');\n");
		fprintf(htmlFile, "                contests.forEach(contest => {\n");
		fprintf(htmlFile, "                    ul.appendChild(generateContestHTML(contest));\n");
		fprintf(htmlFile, "                });\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                section.appendChild(ul);\n");
		fprintf(htmlFile, "                main.appendChild(section);\n");
		fprintf(htmlFile, "            });\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Initialize the page\n");
		fprintf(htmlFile, "        renderClassifiedContests();\n");
		fprintf(htmlFile, "    </script>\n");
		fprintf(htmlFile, "</body>\n");
		fprintf(htmlFile, "</html>\n");
	}


	free(str);
	fclose(htmlFile); // Close file
	open_file(filename);
}


void generate_user_contest_list(cJSON* root, char* handle) {

	char* str = cJSON_Print(root);
	const char* filename = "user_contest_list.html";
	printf("Generating HTML file...\n");
	FILE* htmlFile = fopen(filename, "w"); // Create report.html file
	if (htmlFile == NULL) {
		printf("Failed to create file\n");
		return;
	}

	{
		fprintf(htmlFile, "<!DOCTYPE html>\n");
		fprintf(htmlFile, "<html lang=\"en\">\n");
		fprintf(htmlFile, "<head>\n");
		fprintf(htmlFile, "    <meta charset=\"UTF-8\">\n");
		fprintf(htmlFile, "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
		fprintf(htmlFile, "    <title>User's Contest History</title>\n");
		fprintf(htmlFile, "    <style>\n");
		fprintf(htmlFile, "        body {\n");
		fprintf(htmlFile, "            font-family: Arial, sans-serif;\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "            background-color: #f9f9f9;\n");
		fprintf(htmlFile, "            color: #333;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header {\n");
		fprintf(htmlFile, "            background-color: #4CAF50;\n");
		fprintf(htmlFile, "            color: white;\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header h1 {\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header p {\n");
		fprintf(htmlFile, "            margin: 5px 0 0;\n");
		fprintf(htmlFile, "            font-size: 14px;\n");
		fprintf(htmlFile, "            color: #e0e0e0; /* 浅灰色小字 */\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        main {\n");
		fprintf(htmlFile, "            max-width: 800px;\n");
		fprintf(htmlFile, "            margin: 20px auto;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            background-color: white;\n");
		fprintf(htmlFile, "            border-radius: 8px;\n");
		fprintf(htmlFile, "            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        section {\n");
		fprintf(htmlFile, "            margin-bottom: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        section h2 {\n");
		fprintf(htmlFile, "            font-size: 20px;\n");
		fprintf(htmlFile, "            margin: 0 0 10px;\n");
		fprintf(htmlFile, "            color: #4CAF50;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        ul {\n");
		fprintf(htmlFile, "            list-style-type: none;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        li {\n");
		fprintf(htmlFile, "            background-color: #f1f1f1;\n");
		fprintf(htmlFile, "            margin: 10px 0;\n");
		fprintf(htmlFile, "            padding: 15px;\n");
		fprintf(htmlFile, "            border-radius: 5px;\n");
		fprintf(htmlFile, "            display: flex;\n");
		fprintf(htmlFile, "            justify-content: space-between;\n");
		fprintf(htmlFile, "            align-items: center;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .contest-info {\n");
		fprintf(htmlFile, "            flex-grow: 1;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .contest-name {\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            margin-bottom: 5px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .contest-details {\n");
		fprintf(htmlFile, "            font-size: 14px;\n");
		fprintf(htmlFile, "            color: #666;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .rating-change {\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            color: #4CAF50;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .rating-change.negative {\n");
		fprintf(htmlFile, "            color: #FF5252; /* 红色表示负变化 */\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </style>\n");
		fprintf(htmlFile, "</head>\n");
		fprintf(htmlFile, "<body>\n");
		fprintf(htmlFile, "    <header>\n");
		fprintf(htmlFile, "        <h1>User's Contest History</h1>\n");
		fprintf(htmlFile, "        <p>Participated contests grouped by Divisions</p>\n");
		fprintf(htmlFile, "    </header>\n");
		fprintf(htmlFile, "    <main>\n");
		fprintf(htmlFile, "        <!-- 动态生成的分组内容 -->\n");
		fprintf(htmlFile, "    </main>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "    <script>\n");
		fprintf(htmlFile, "        const data = %s;\n", str);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        function formatDate(timestamp) {\n");
		fprintf(htmlFile, "            const date = new Date(timestamp * 1000);\n");
		fprintf(htmlFile, "            return date.toLocaleString();\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // 分组函数\n");
		fprintf(htmlFile, "        function groupByDivision(contests) {\n");
		fprintf(htmlFile, "            const groups = {};\n");
		fprintf(htmlFile, "            contests.forEach(contest => {\n");
		fprintf(htmlFile, "                // 提取Div信息，例如Div. 1 Only -> Div 1\"\n");
		fprintf(htmlFile, "                const divMatch = contest.contestName.match(/Div\\. (\\d+)/);\n");
		fprintf(htmlFile, "                const div = divMatch ? `Div ${divMatch[1]}` :\" Other\"; // 使用字符串Other\"\n");
		fprintf(htmlFile, "                if (!groups[div]) {\n");
		fprintf(htmlFile, "                    groups[div] = [];\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "                groups[div].push(contest);\n");
		fprintf(htmlFile, "            });\n");
		fprintf(htmlFile, "            return groups;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // 渲染分组内容\n");
		fprintf(htmlFile, "        function renderContestGroups(groups) {\n");
		fprintf(htmlFile, "            const main = document.querySelector('main');\n");
		fprintf(htmlFile, "            for (const [div, contests] of Object.entries(groups)) {\n");
		fprintf(htmlFile, "                const section = document.createElement('section');\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                const h2 = document.createElement('h2');\n");
		fprintf(htmlFile, "                h2.textContent = `${div} Contests`;\n");
		fprintf(htmlFile, "                section.appendChild(h2);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                const ul = document.createElement('ul');\n");
		fprintf(htmlFile, "                contests.forEach(contest => {\n");
		fprintf(htmlFile, "                    const li = document.createElement('li');\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    const infoDiv = document.createElement('div');\n");
		fprintf(htmlFile, "                    infoDiv.className = 'contest-info';\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    const nameSpan = document.createElement('span');\n");
		fprintf(htmlFile, "                    nameSpan.className = 'contest-name';\n");
		fprintf(htmlFile, "                    nameSpan.textContent = contest.contestName;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    const detailsDiv = document.createElement('div');\n");
		fprintf(htmlFile, "                    detailsDiv.className = 'contest-details';\n");
		fprintf(htmlFile, "                    detailsDiv.innerHTML = `\n");
		fprintf(htmlFile, "                        Rank: ${contest.rank}<br>\n");
		fprintf(htmlFile, "                        Rating Change: ${contest.oldRating} --> ${contest.newRating}<br>\n");
		fprintf(htmlFile, "                        Updated: ${formatDate(contest.ratingUpdateTimeSeconds)}\n");
		fprintf(htmlFile, "                    `;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    infoDiv.appendChild(nameSpan);\n");
		fprintf(htmlFile, "                    infoDiv.appendChild(detailsDiv);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    const ratingChangeSpan = document.createElement('span');\n");
		fprintf(htmlFile, "                    const ratingChange = contest.newRating - contest.oldRating;\n");
		fprintf(htmlFile, "                    ratingChangeSpan.className = `rating-change ${ratingChange < 0 ? 'negative' : ''}`;\n");
		fprintf(htmlFile, "                    ratingChangeSpan.textContent = `${ratingChange > 0 ? '+' : ''}${ratingChange}`;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    li.appendChild(infoDiv);\n");
		fprintf(htmlFile, "                    li.appendChild(ratingChangeSpan);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    ul.appendChild(li);\n");
		fprintf(htmlFile, "                });\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                section.appendChild(ul);\n");
		fprintf(htmlFile, "                main.appendChild(section);\n");
		fprintf(htmlFile, "            }\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // 主逻辑\n");
		fprintf(htmlFile, "        try {\n");
		fprintf(htmlFile, "            const groupedContests = groupByDivision(data.result);\n");
		fprintf(htmlFile, "            renderContestGroups(groupedContests);\n");
		fprintf(htmlFile, "        } catch (error) {\n");
		fprintf(htmlFile, "            console.error(\"Error processing data:\", error);\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </script>\n");
		fprintf(htmlFile, "</body>\n");
		fprintf(htmlFile, "</html>\n");

	}




	free(str);
	fclose(htmlFile); // Close file
	open_file(filename);
}


void generate_user_performance(cJSON* list, cJSON* detail) {
	char* str_list = cJSON_Print(list);
	char* str_detail = cJSON_Print(detail);
	const char* filename = "user_contest_performance.html";
	printf("Generating HTML file...\n");
	FILE* htmlFile = fopen(filename, "w"); // Create report.html file
	if (htmlFile == NULL) {
		printf("Failed to create file\n");
		return;
	}

	{
		fprintf(htmlFile, "<!DOCTYPE html>\n");
		fprintf(htmlFile, "<html lang=\"en\">\n");
		fprintf(htmlFile, "<head>\n");
		fprintf(htmlFile, "    <meta charset=\"UTF-8\">\n");
		fprintf(htmlFile, "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
		fprintf(htmlFile, "    <title>Codeforces User Contest Performance</title>\n");
		fprintf(htmlFile, "    <style>\n");
		fprintf(htmlFile, "        body {\n");
		fprintf(htmlFile, "            font-family: Arial, sans-serif;\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "            background-color: #f9f9f9;\n");
		fprintf(htmlFile, "            color: #333;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header {\n");
		fprintf(htmlFile, "            background-color: #4CAF50;\n");
		fprintf(htmlFile, "            color: white;\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header h1 {\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        main {\n");
		fprintf(htmlFile, "            max-width: 800px;\n");
		fprintf(htmlFile, "            margin: 20px auto;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            background-color: white;\n");
		fprintf(htmlFile, "            border-radius: 8px;\n");
		fprintf(htmlFile, "            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        section {\n");
		fprintf(htmlFile, "            margin-bottom: 30px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        h2 {\n");
		fprintf(htmlFile, "            font-size: 20px;\n");
		fprintf(htmlFile, "            color: #4CAF50;\n");
		fprintf(htmlFile, "            margin-bottom: 10px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        table {\n");
		fprintf(htmlFile, "            width: 100%;\n");
		fprintf(htmlFile, "            border-collapse: collapse;\n");
		fprintf(htmlFile, "            margin-top: 10px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        th, td {\n");
		fprintf(htmlFile, "            border: 1px solid #ddd;\n");
		fprintf(htmlFile, "            padding: 8px;\n");
		fprintf(htmlFile, "            text-align: left;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        th {\n");
		fprintf(htmlFile, "            background-color: #f2f2f2;\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .rating-change {\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            color: #4CAF50;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .negative-change {\n");
		fprintf(htmlFile, "            color: red;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </style>\n");
		fprintf(htmlFile, "</head>\n");
		fprintf(htmlFile, "<body>\n");
		fprintf(htmlFile, "    <header>\n");
		fprintf(htmlFile, "        <h1>Codeforces User Contest Performance</h1>\n");
		fprintf(htmlFile, "        <p>Details of user's performance in multiple contests</p>\n");
		fprintf(htmlFile, "    </header>\n");
		fprintf(htmlFile, "    <main id=main-content>\n");
		fprintf(htmlFile, "        <!-- Content will be dynamically generated here -->\n");
		fprintf(htmlFile, "    </main>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "    <script>\n");
		fprintf(htmlFile, "        // Mock API responses\n");
		fprintf(htmlFile, "        const ratingData = %s;\n",str_list);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        const contestData = %s;\n",str_detail);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Function to generate the HTML content for a single contest\n");
		fprintf(htmlFile, "        function generateContestHTML(contest, ratingInfo) {\n");
		fprintf(htmlFile, "            const contestSection = document.createElement('section');\n");
		fprintf(htmlFile, "            contestSection.innerHTML = `\n");
		fprintf(htmlFile, "                <h2>${contest.contest.name}</h2>\n");
		fprintf(htmlFile, "                <p><strong>Rank:</strong> ${contest.rows[0].rank}</p>\n");
		fprintf(htmlFile, "                <p><strong>Total Points:</strong> ${contest.rows[0].points}</p>\n");
		fprintf(htmlFile, "                <p><strong>Old Rating:</strong> ${ratingInfo.oldRating}</p>\n");
		fprintf(htmlFile, "                <p><strong>New Rating:</strong> ${ratingInfo.newRating}</p>\n");
		fprintf(htmlFile, "                <p><strong>Rating Change:</strong> \n");
		fprintf(htmlFile, "                    <span class=${ratingInfo.newRating > ratingInfo.oldRating ? 'rating-change' : 'negative-change'}>\n");
		fprintf(htmlFile, "                        ${ratingInfo.newRating - ratingInfo.oldRating > 0 ? '+' : ''}${ratingInfo.newRating - ratingInfo.oldRating}\n");
		fprintf(htmlFile, "                    </span>\n");
		fprintf(htmlFile, "                </p>\n");
		fprintf(htmlFile, "            `;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Create problem scores table\n");
		fprintf(htmlFile, "            const table = document.createElement('table');\n");
		fprintf(htmlFile, "            const thead = document.createElement('thead');\n");
		fprintf(htmlFile, "            thead.innerHTML = `\n");
		fprintf(htmlFile, "                <tr>\n");
		fprintf(htmlFile, "                    <th>Problem</th>\n");
		fprintf(htmlFile, "                    <th>Name</th>\n");
		fprintf(htmlFile, "                    <th>Max Points</th>\n");
		fprintf(htmlFile, "                    <th>Earned Points</th>\n");
		fprintf(htmlFile, "                </tr>\n");
		fprintf(htmlFile, "            `;\n");
		fprintf(htmlFile, "            table.appendChild(thead);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const tbody = document.createElement('tbody');\n");
		fprintf(htmlFile, "            contest.problems.forEach((problem, index) => {\n");
		fprintf(htmlFile, "                const earnedPoints = contest.rows[0].problemResults[index].points || 0;\n");
		fprintf(htmlFile, "                const row = document.createElement('tr');\n");
		fprintf(htmlFile, "                row.innerHTML = `\n");
		fprintf(htmlFile, "                    <td>${problem.index}</td>\n");
		fprintf(htmlFile, "                    <td>${problem.name}</td>\n");
		fprintf(htmlFile, "                    <td>${problem.points}</td>\n");
		fprintf(htmlFile, "                    <td>${earnedPoints}</td>\n");
		fprintf(htmlFile, "                `;\n");
		fprintf(htmlFile, "                tbody.appendChild(row);\n");
		fprintf(htmlFile, "            });\n");
		fprintf(htmlFile, "            table.appendChild(tbody);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            contestSection.appendChild(table);\n");
		fprintf(htmlFile, "            return contestSection;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Main function to render all contests\n");
		fprintf(htmlFile, "        function renderAllContests() {\n");
		fprintf(htmlFile, "            const mainContent = document.getElementById('main-content');\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            contestData.result.forEach(contest => {\n");
		fprintf(htmlFile, "                const contestId = contest.contest.id;\n");
		fprintf(htmlFile, "                const ratingInfo = ratingData.result.find(rating => rating.contestId === contestId);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                if (ratingInfo) {\n");
		fprintf(htmlFile, "                    const contestHTML = generateContestHTML(contest, ratingInfo);\n");
		fprintf(htmlFile, "                    mainContent.appendChild(contestHTML);\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            });\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Initialize the page\n");
		fprintf(htmlFile, "        renderAllContests();\n");
		fprintf(htmlFile, "    </script>\n");
		fprintf(htmlFile, "</body>\n");
		fprintf(htmlFile, "</html>\n");
	

}


	free(str_list);
	free(str_detail);
	fclose(htmlFile); // Close file
	open_file(filename);
}


void generate_user_information(cJSON* root) {
	char* str = cJSON_Print(root);
	
	const char* filename = "user_information.html";
	printf("Generating HTML file...\n");
	FILE* htmlFile = fopen(filename, "w"); // Create report.html file
	if (htmlFile == NULL) {
		printf("Failed to create file\n");
		return;
	}

	{
		fprintf(htmlFile, "<!DOCTYPE html>\n");
		fprintf(htmlFile, "<html lang=\"en\">\n");
		fprintf(htmlFile, "<head>\n");
		fprintf(htmlFile, "    <meta charset=\"UTF-8\">\n");
		fprintf(htmlFile, "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
		fprintf(htmlFile, "    <title>User Contest Performance Visualization</title>\n");
		fprintf(htmlFile, "    <script src=\"https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js\"></script>\n");
		fprintf(htmlFile, "    <style>\n");
		fprintf(htmlFile, "        body {\n");
		fprintf(htmlFile, "            font-family: Arial, sans-serif;\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "            background-color: #f9f9f9;\n");
		fprintf(htmlFile, "            color: #333;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header {\n");
		fprintf(htmlFile, "            background-color: #4CAF50;\n");
		fprintf(htmlFile, "            color: white;\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header h1 {\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        main {\n");
		fprintf(htmlFile, "            max-width: 1200px;\n");
		fprintf(htmlFile, "            margin: 20px auto;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            background-color: white;\n");
		fprintf(htmlFile, "            border-radius: 8px;\n");
		fprintf(htmlFile, "            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .chart-container {\n");
		fprintf(htmlFile, "            margin-bottom: 40px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .chart {\n");
		fprintf(htmlFile, "            width: 100%%;\n");
		fprintf(htmlFile, "            height: 400px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </style>\n");
		fprintf(htmlFile, "</head>\n");
		fprintf(htmlFile, "<body>\n");
		fprintf(htmlFile, "    <header>\n");
		fprintf(htmlFile, "        <h1>User Contest Performance Visualization</h1>\n");
		fprintf(htmlFile, "        <p>Graphical representation of user's contest participation and performance</p>\n");
		fprintf(htmlFile, "    </header>\n");
		fprintf(htmlFile, "    <main>\n");
		fprintf(htmlFile, "        <!-- Attendance Rate Chart -->\n");
		fprintf(htmlFile, "        <div class=\"chart-container\">\n");
		fprintf(htmlFile, "            <h2>Attendance Rate</h2>\n");
		fprintf(htmlFile, "            <div id=\"attendance-rate-chart\" class=\"chart\"></div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        <!-- Division Participation Chart -->\n");
		fprintf(htmlFile, "        <div class=\"chart-container\">\n");
		fprintf(htmlFile, "            <h2>Division Participation</h2>\n");
		fprintf(htmlFile, "            <div id=\"division-participation-chart\" class=\"chart\"></div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        <!-- Monthly Participation Chart -->\n");
		fprintf(htmlFile, "        <div class=\"chart-container\">\n");
		fprintf(htmlFile, "            <h2>Monthly Participation</h2>\n");
		fprintf(htmlFile, "            <div id=\"monthly-participation-chart\" class=\"chart\"></div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "    </main>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "    <script>\n");
		fprintf(htmlFile, "        // Mock JSON data\n");
		fprintf(htmlFile, "        const userData = %s;\n",str);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Initialize ECharts instances\n");
		fprintf(htmlFile, "        const attendanceRateChart = echarts.init(document.getElementById('attendance-rate-chart'));\n");
		fprintf(htmlFile, "        const divisionParticipationChart = echarts.init(document.getElementById('division-participation-chart'));\n");
		fprintf(htmlFile, "        const monthlyParticipationChart = echarts.init(document.getElementById('monthly-participation-chart'));\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Attendance Rate Chart Configuration\n");
		fprintf(htmlFile, "        const attendanceRateOption = {\n");
		fprintf(htmlFile, "            title: {\n");
		fprintf(htmlFile, "                text: 'Attendance Rate',\n");
		fprintf(htmlFile, "                left: 'center'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            tooltip: {\n");
		fprintf(htmlFile, "                trigger: 'item'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            series: [\n");
		fprintf(htmlFile, "                {\n");
		fprintf(htmlFile, "                    type: 'gauge',\n");
		fprintf(htmlFile, "                    detail: { formatter: '{value}\%' },\n");
		fprintf(htmlFile, "                    data: [{ value: userData.attendance_rate.toFixed(2), name: 'Attendance Rate' }],\n");
		fprintf(htmlFile, "                    min: 0,\n");
		fprintf(htmlFile, "                    max: 100,\n");
		fprintf(htmlFile, "                    splitNumber: 10,\n");
		fprintf(htmlFile, "                    radius: '75%%',\n");
		fprintf(htmlFile, "                    axisLine: {\n");
		fprintf(htmlFile, "                        lineStyle: {\n");
		fprintf(htmlFile, "                            width: 10,\n");
		fprintf(htmlFile, "                            color: [\n");
		fprintf(htmlFile, "                                [0.2, '#ff4500'],\n");
		fprintf(htmlFile, "                                [0.8, '#4caf50'],\n");
		fprintf(htmlFile, "                                [1, '#2196f3']\n");
		fprintf(htmlFile, "                            ]\n");
		fprintf(htmlFile, "                        }\n");
		fprintf(htmlFile, "                    }\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            ]\n");
		fprintf(htmlFile, "        };\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Division Participation Chart Configuration\n");
		fprintf(htmlFile, "        const divisionParticipationOption = {\n");
		fprintf(htmlFile, "            title: {\n");
		fprintf(htmlFile, "                text: 'Division Participation',\n");
		fprintf(htmlFile, "                left: 'center'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            tooltip: {\n");
		fprintf(htmlFile, "                trigger: 'item',\n");
		fprintf(htmlFile, "                formatter: '{a} <br/>{b}: {c} ({d}\\%%)'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            legend: {\n");
		fprintf(htmlFile, "                orient: 'vertical',\n");
		fprintf(htmlFile, "                left: 'left'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            series: [\n");
		fprintf(htmlFile, "                {\n");
		fprintf(htmlFile, "                    name: 'Divisions',\n");
		fprintf(htmlFile, "                    type: 'pie',\n");
		fprintf(htmlFile, "                    radius: ['40%%', '70%%'],\n");
		fprintf(htmlFile, "                    avoidLabelOverlap: false,\n");
		fprintf(htmlFile, "                    label: {\n");
		fprintf(htmlFile, "                        show: false,\n");
		fprintf(htmlFile, "                        position: 'center'\n");
		fprintf(htmlFile, "                    },\n");
		fprintf(htmlFile, "                    emphasis: {\n");
		fprintf(htmlFile, "                        label: {\n");
		fprintf(htmlFile, "                            show: true,\n");
		fprintf(htmlFile, "                            fontSize: 20,\n");
		fprintf(htmlFile, "                            fontWeight: 'bold'\n");
		fprintf(htmlFile, "                        }\n");
		fprintf(htmlFile, "                    },\n");
		fprintf(htmlFile, "                    data: [\n");
		fprintf(htmlFile, "                        { value: userData.user_attend_div1, name: 'Div 1' },\n");
		fprintf(htmlFile, "                        { value: userData.user_attend_div2, name: 'Div 2' },\n");
		fprintf(htmlFile, "                        { value: userData.user_attend_div3, name: 'Div 3' },\n");
		fprintf(htmlFile, "                        { value: userData.user_attend_div4, name: 'Div 4' }\n");
		fprintf(htmlFile, "                    ]\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            ]\n");
		fprintf(htmlFile, "        };\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Monthly Participation Chart Configuration\n");
		fprintf(htmlFile, "        const monthlyParticipationOption = {\n");
		fprintf(htmlFile, "            title: {\n");
		fprintf(htmlFile, "                text: 'Monthly Participation',\n");
		fprintf(htmlFile, "                left: 'center'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            tooltip: {\n");
		fprintf(htmlFile, "                trigger: 'axis'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            xAxis: {\n");
		fprintf(htmlFile, "                type: 'category',\n");
		fprintf(htmlFile, "                data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            yAxis: {\n");
		fprintf(htmlFile, "                type: 'value'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            series: [\n");
		fprintf(htmlFile, "                {\n");
		fprintf(htmlFile, "                    data: userData.month,\n");
		fprintf(htmlFile, "                    type: 'bar',\n");
		fprintf(htmlFile, "                    label: {\n");
		fprintf(htmlFile, "                        show: true,\n");
		fprintf(htmlFile, "                        position: 'top'\n");
		fprintf(htmlFile, "                    }\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            ]\n");
		fprintf(htmlFile, "        };\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Set options to charts\n");
		fprintf(htmlFile, "        attendanceRateChart.setOption(attendanceRateOption);\n");
		fprintf(htmlFile, "        divisionParticipationChart.setOption(divisionParticipationOption);\n");
		fprintf(htmlFile, "        monthlyParticipationChart.setOption(monthlyParticipationOption);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Responsive layout\n");
		fprintf(htmlFile, "        window.addEventListener('resize', () => {\n");
		fprintf(htmlFile, "            attendanceRateChart.resize();\n");
		fprintf(htmlFile, "            divisionParticipationChart.resize();\n");
		fprintf(htmlFile, "            monthlyParticipationChart.resize();\n");
		fprintf(htmlFile, "        });\n");
		fprintf(htmlFile, "    </script>\n");
		fprintf(htmlFile, "</body>\n");
		fprintf(htmlFile, "</html>\n");
	}


	free(str);
	fclose(htmlFile); // Close file
	open_file(filename);
}


void generate_user_contest_summary(cJSON* list, cJSON* detail) {
	char* str_list = cJSON_Print(list);
	char* str_detail = cJSON_Print(detail);
	const char* filename = "user_contest_summary.html";
	printf("Generating HTML file...\n");
	FILE* htmlFile = fopen(filename, "w"); // Create report.html file
	if (htmlFile == NULL) {
		printf("Failed to create file\n");
		return;
	}

	{
		fprintf(htmlFile, "<!DOCTYPE html>\n");
		fprintf(htmlFile, "<html lang=\"en\">\n");
		fprintf(htmlFile, "<head>\n");
		fprintf(htmlFile, "    <meta charset=\"UTF-8\">\n");
		fprintf(htmlFile, "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
		fprintf(htmlFile, "    <title>User Contest Performance</title>\n");
		fprintf(htmlFile, "    <script src=\"https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js\"></script>\n");
		fprintf(htmlFile, "    <style>\n");
		fprintf(htmlFile, "        body {\n");
		fprintf(htmlFile, "            font-family: Arial, sans-serif;\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "            background-color: #f9f9f9;\n");
		fprintf(htmlFile, "            color: #333;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header {\n");
		fprintf(htmlFile, "            background-color: #4CAF50;\n");
		fprintf(htmlFile, "            color: white;\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header h1 {\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        main {\n");
		fprintf(htmlFile, "            max-width: 1200px;\n");
		fprintf(htmlFile, "            margin: 20px auto;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            background-color: white;\n");
		fprintf(htmlFile, "            border-radius: 8px;\n");
		fprintf(htmlFile, "            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .chart-container {\n");
		fprintf(htmlFile, "            margin-bottom: 40px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .chart {\n");
		fprintf(htmlFile, "            width: 100%%;\n");
		fprintf(htmlFile, "            height: 400px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        table {\n");
		fprintf(htmlFile, "            width: 100%%;\n");
		fprintf(htmlFile, "            border-collapse: collapse;\n");
		fprintf(htmlFile, "            margin-top: 10px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        th, td {\n");
		fprintf(htmlFile, "            border: 1px solid #ddd;\n");
		fprintf(htmlFile, "            padding: 8px;\n");
		fprintf(htmlFile, "            text-align: left;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        th {\n");
		fprintf(htmlFile, "            background-color: #f2f2f2;\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .rating-change {\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "            color: #4CAF50;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .negative-change {\n");
		fprintf(htmlFile, "            color: red;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </style>\n");
		fprintf(htmlFile, "</head>\n");
		fprintf(htmlFile, "<body>\n");
		fprintf(htmlFile, "    <header>\n");
		fprintf(htmlFile, "        <h1>User Contest Performance</h1>\n");
		fprintf(htmlFile, "        <p>Details of user's participation in all contests</p>\n");
		fprintf(htmlFile, "    </header>\n");
		fprintf(htmlFile, "    <main>\n");
		fprintf(htmlFile, "        <!-- Rating Change Chart -->\n");
		fprintf(htmlFile, "        <div class=\"chart-container\">\n");
		fprintf(htmlFile, "            <h2>Rating Changes Over Time</h2>\n");
		fprintf(htmlFile, "            <div id=\"rating-change-chart\" class=\"chart\"></div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        <!-- Contest Details Table -->\n");
		fprintf(htmlFile, "        <section>\n");
		fprintf(htmlFile, "            <h2>Contest Details</h2>\n");
		fprintf(htmlFile, "            <table id=\"contest-details-table\">\n");
		fprintf(htmlFile, "                <thead>\n");
		fprintf(htmlFile, "                    <tr>\n");
		fprintf(htmlFile, "                        <th>Level</th>\n");
		fprintf(htmlFile, "                        <th>Name</th>\n");
		fprintf(htmlFile, "                        <th>Date</th>\n");
		fprintf(htmlFile, "                        <th>Rank</th>\n");
		fprintf(htmlFile, "                        <th>Problem Scores</th>\n");
		fprintf(htmlFile, "                        <th>Rating Change</th>\n");
		fprintf(htmlFile, "                        <th>Title Change</th>\n");
		fprintf(htmlFile, "                    </tr>\n");
		fprintf(htmlFile, "                </thead>\n");
		fprintf(htmlFile, "                <tbody></tbody>\n");
		fprintf(htmlFile, "            </table>\n");
		fprintf(htmlFile, "        </section>\n");
		fprintf(htmlFile, "    </main>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "    <script>\n");
		fprintf(htmlFile, "        // Mock JSON data\n");		fprintf(htmlFile, "        const ratingData = %s;\n", str_list);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        const contestData = %s;\n", str_detail);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Initialize ECharts instance for Rating Change Chart\n");
		fprintf(htmlFile, "        const ratingChangeChart = echarts.init(document.getElementById('rating-change-chart'));\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Format date from timestamp\n");
		fprintf(htmlFile, "        function formatDate(timestamp) {\n");
		fprintf(htmlFile, "            return new Date(timestamp * 1000).toLocaleDateString();\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Define title mapping based on Codeforces rating ranges\n");
		fprintf(htmlFile, "        const titleMapping = [\n");
		fprintf(htmlFile, "            { min: 3000, title: \"Legendary Grandmaster\" },\n");
		fprintf(htmlFile, "            { min: 2600, title: \"International Grandmaster\" },\n");
		fprintf(htmlFile, "            { min: 2400, title: \"Grandmaster\" },\n");
		fprintf(htmlFile, "            { min: 2300, title: \"International Master\" },\n");
		fprintf(htmlFile, "            { min: 2100, title: \"Master\" },\n");
		fprintf(htmlFile, "            { min: 1900, title: \"Candidate Master\" },\n");
		fprintf(htmlFile, "            { min: 1600, title: \"Expert\" },\n");
		fprintf(htmlFile, "            { min: 1400, title: \"Specialist\" },\n");
		fprintf(htmlFile, "            { min: 1200, title: \"Pupil\" },\n");
		fprintf(htmlFile, "            { min: -Infinity, title: \"Newbie\" } // Catch-all for ratings below 1200\n");
		fprintf(htmlFile, "        ];\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Function to get title based on rating\n");
		fprintf(htmlFile, "        function getTitleFromRating(rating) {\n");
		fprintf(htmlFile, "            for (const { min, title } of titleMapping) {\n");
		fprintf(htmlFile, "                if (rating >= min) {\n");
		fprintf(htmlFile, "                    return title;\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            }\n");
		fprintf(htmlFile, "            return \"Unknown\"; // Fallback in case no match is found\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Generate Rating Change Chart Configuration\n");
		fprintf(htmlFile, "        const ratingChangeOption = {\n");
		fprintf(htmlFile, "            title: {\n");
		fprintf(htmlFile, "                text: 'Rating Changes Over Time',\n");
		fprintf(htmlFile, "                left: 'center'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            tooltip: {\n");
		fprintf(htmlFile, "                trigger: 'axis'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            xAxis: {\n");
		fprintf(htmlFile, "                type: 'category',\n");
		fprintf(htmlFile, "                data: ratingData.result.map(rating => formatDate(rating.ratingUpdateTimeSeconds))\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            yAxis: {\n");
		fprintf(htmlFile, "                type: 'value'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            series: [\n");
		fprintf(htmlFile, "                {\n");
		fprintf(htmlFile, "                    name: 'Rating',\n");
		fprintf(htmlFile, "                    type: 'line',\n");
		fprintf(htmlFile, "                    data: ratingData.result.map(rating => rating.newRating),\n");
		fprintf(htmlFile, "                    markPoint: {\n");
		fprintf(htmlFile, "                        data: [\n");
		fprintf(htmlFile, "                            { type: 'max', name: 'Max' },\n");
		fprintf(htmlFile, "                            { type: 'min', name: 'Min' }\n");
		fprintf(htmlFile, "                        ]\n");
		fprintf(htmlFile, "                    },\n");
		fprintf(htmlFile, "                    markLine: {\n");
		fprintf(htmlFile, "                        data: [{ type: 'average', name: 'Average' }]\n");
		fprintf(htmlFile, "                    }\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            ]\n");
		fprintf(htmlFile, "        };\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Set options to chart\n");
		fprintf(htmlFile, "        ratingChangeChart.setOption(ratingChangeOption);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Populate Contest Details Table\n");
		fprintf(htmlFile, "        const tableBody = document.querySelector('#contest-details-table tbody');\n");
		fprintf(htmlFile, "        contestData.result.forEach((contest, index) => {\n");
		fprintf(htmlFile, "            const ratingInfo = ratingData.result.find(rating => rating.contestId === contest.contest.id);\n");
		fprintf(htmlFile, "            const row = document.createElement('tr');\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Level\n");
		fprintf(htmlFile, "            const levelCell = document.createElement('td');\n");
		fprintf(htmlFile, "            levelCell.textContent = contest.contest.name.includes(\"Div. 1\") ? \"Div. 1\"\n");
		fprintf(htmlFile, "                : contest.contest.name.includes(\"Div. 2\") ? \"Div. 2\"\n");
		fprintf(htmlFile, "                : contest.contest.name.includes(\"Div. 3\") ? \"Div. 3\"\n");
		fprintf(htmlFile, "                : \"Div. 4\";\n");
		fprintf(htmlFile, "            row.appendChild(levelCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Name\n");
		fprintf(htmlFile, "            const nameCell = document.createElement('td');\n");
		fprintf(htmlFile, "            nameCell.textContent = contest.contest.name;\n");
		fprintf(htmlFile, "            row.appendChild(nameCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Date\n");
		fprintf(htmlFile, "            const dateCell = document.createElement('td');\n");
		fprintf(htmlFile, "            dateCell.textContent = formatDate(contest.contest.startTimeSeconds);\n");
		fprintf(htmlFile, "            row.appendChild(dateCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Rank\n");
		fprintf(htmlFile, "            const rankCell = document.createElement('td');\n");
		fprintf(htmlFile, "            rankCell.textContent = contest.rows[0].rank;\n");
		fprintf(htmlFile, "            row.appendChild(rankCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Problem Scores\n");
		fprintf(htmlFile, "            const problemScoresCell = document.createElement('td');\n");
		fprintf(htmlFile, "            const scores = contest.rows[0].problemResults.map(result => result.points || 0).join(', ');\n");
		fprintf(htmlFile, "            problemScoresCell.textContent = `[${scores}]`;\n");
		fprintf(htmlFile, "            row.appendChild(problemScoresCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Rating Change\n");
		fprintf(htmlFile, "            const ratingChangeCell = document.createElement('td');\n");
		fprintf(htmlFile, "            const ratingChange = ratingInfo.newRating - ratingInfo.oldRating;\n");
		fprintf(htmlFile, "            ratingChangeCell.innerHTML = `<span class=\"${ratingChange > 0 ? 'rating-change' : 'negative-change'}\">${ratingChange > 0 ? '+' : ''}${ratingChange}</span>`;\n");
		fprintf(htmlFile, "            row.appendChild(ratingChangeCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            // Title Change (Assuming title changes are not provided, we use placeholders)\n");
		fprintf(htmlFile, "            const titleChangeCell = document.createElement('td');\n");
		fprintf(htmlFile, "            const oldTitle = getTitleFromRating(ratingInfo.oldRating);\n");
		fprintf(htmlFile, "            const newTitle = getTitleFromRating(ratingInfo.newRating);\n");
		fprintf(htmlFile, "            titleChangeCell.textContent = `${oldTitle} -> ${newTitle}`;\n");
		fprintf(htmlFile, "            row.appendChild(titleChangeCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            tableBody.appendChild(row);\n");
		fprintf(htmlFile, "        });\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Responsive layout\n");
		fprintf(htmlFile, "        window.addEventListener('resize', () => {\n");
		fprintf(htmlFile, "            ratingChangeChart.resize();\n");
		fprintf(htmlFile, "        });\n");
		fprintf(htmlFile, "    </script>\n");
		fprintf(htmlFile, "</body>\n");
		fprintf(htmlFile, "</html>\n");

	}


	free(str_list);
	free(str_detail);
	fclose(htmlFile); // Close file
	open_file(filename);
}


void generate_analyze_contest_problem_statistics(cJSON* root) {

	char* str = cJSON_Print(root);

	const char* filename = "analyze_contest_problem_statistics.html";
	printf("Generating HTML file...\n");
	FILE* htmlFile = fopen(filename, "w"); // Create report.html file
	if (htmlFile == NULL) {
		printf("Failed to create file\n");
		return;
	}

	{


		fprintf(htmlFile, "<!DOCTYPE html>\n");
		fprintf(htmlFile, "<html lang=\"en\">\n");
		fprintf(htmlFile, "<head>\n");
		fprintf(htmlFile, "    <meta charset=\"UTF-8\">\n");
		fprintf(htmlFile, "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
		fprintf(htmlFile, "    <title>Codeforces Contest Analysis</title>\n");
		fprintf(htmlFile, "    <script src=\"https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js\"></script>\n");
		fprintf(htmlFile, "    <style>\n");
		fprintf(htmlFile, "        body {\n");
		fprintf(htmlFile, "            font-family: Arial, sans-serif;\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            padding: 0;\n");
		fprintf(htmlFile, "            background-color: #f9f9f9;\n");
		fprintf(htmlFile, "            color: #333;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header {\n");
		fprintf(htmlFile, "            background-color: #4CAF50;\n");
		fprintf(htmlFile, "            color: white;\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        header h1 {\n");
		fprintf(htmlFile, "            margin: 0;\n");
		fprintf(htmlFile, "            font-size: 24px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        main {\n");
		fprintf(htmlFile, "            max-width: 1200px;\n");
		fprintf(htmlFile, "            margin: 20px auto;\n");
		fprintf(htmlFile, "            padding: 20px;\n");
		fprintf(htmlFile, "            background-color: white;\n");
		fprintf(htmlFile, "            border-radius: 8px;\n");
		fprintf(htmlFile, "            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .chart-container {\n");
		fprintf(htmlFile, "            margin-bottom: 40px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .chart {\n");
		fprintf(htmlFile, "            width: 100%%;\n");
		fprintf(htmlFile, "            height: 400px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        table {\n");
		fprintf(htmlFile, "            width: 100%%;\n");
		fprintf(htmlFile, "            border-collapse: collapse;\n");
		fprintf(htmlFile, "            margin-top: 10px;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        th, td {\n");
		fprintf(htmlFile, "            border: 1px solid #ddd;\n");
		fprintf(htmlFile, "            padding: 8px;\n");
		fprintf(htmlFile, "            text-align: left;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        th {\n");
		fprintf(htmlFile, "            background-color: #f2f2f2;\n");
		fprintf(htmlFile, "            font-weight: bold;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "        .variance-display {\n");
		fprintf(htmlFile, "            text-align: center;\n");
		fprintf(htmlFile, "            margin-top: 20px;\n");
		fprintf(htmlFile, "            font-size: 18px;\n");
		fprintf(htmlFile, "            color: #555;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "    </style>\n");
		fprintf(htmlFile, "</head>\n");
		fprintf(htmlFile, "<body>\n");
		fprintf(htmlFile, "    <header>\n");
		fprintf(htmlFile, "        <h1>Codeforces Contest Analysis</h1>\n");
		fprintf(htmlFile, "        <p>Statistics on problem accuracy and point distribution across contests</p>\n");
		fprintf(htmlFile, "    </header>\n");
		fprintf(htmlFile, "    <main>\n");
		fprintf(htmlFile, "        <!-- Problem Point Distribution Chart -->\n");
		fprintf(htmlFile, "        <div class=\"chart-container\">\n");
		fprintf(htmlFile, "            <h2>Problem Point Distribution (All Contests)</h2>\n");
		fprintf(htmlFile, "            <div id=\"point-distribution-chart\" class=\"chart\"></div>\n");
		fprintf(htmlFile, "            <!-- Display Variance Separately -->\n");
		fprintf(htmlFile, "            <div class=\"variance-display\">\n");
		fprintf(htmlFile, "                <strong>Variance:</strong> <span id=\"variance-value\">N/A</span>\n");
		fprintf(htmlFile, "            </div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        <!-- Problem Accuracy Chart -->\n");
		fprintf(htmlFile, "        <div class=\"chart-container\">\n");
		fprintf(htmlFile, "            <h2>Problem Accuracy Across Contests</h2>\n");
		fprintf(htmlFile, "            <div id=\"accuracy-chart\" class=\"chart\"></div>\n");
		fprintf(htmlFile, "        </div>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        <!-- Detailed Statistics Table -->\n");
		fprintf(htmlFile, "        <section>\n");
		fprintf(htmlFile, "            <h2>Detailed Problem Statistics</h2>\n");
		fprintf(htmlFile, "            <table id=\"problem-statistics-table\">\n");
		fprintf(htmlFile, "                <thead>\n");
		fprintf(htmlFile, "                    <tr>\n");
		fprintf(htmlFile, "                        <th>Contest Name</th>\n");
		fprintf(htmlFile, "                        <th>Problem Index</th>\n");
		fprintf(htmlFile, "                        <th>Max Points</th>\n");
		fprintf(htmlFile, "                        <th>Average Points</th>\n");
		fprintf(htmlFile, "                        <th>Accuracy (%%)</th>\n");
		fprintf(htmlFile, "                    </tr>\n");
		fprintf(htmlFile, "                </thead>\n");
		fprintf(htmlFile, "                <tbody></tbody>\n");
		fprintf(htmlFile, "            </table>\n");
		fprintf(htmlFile, "        </section>\n");
		fprintf(htmlFile, "    </main>\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "    <script>\n");
		fprintf(htmlFile, "        // Mock JSON data\n");
		fprintf(htmlFile, "        const contestData = %s;\n",str);
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Initialize ECharts instances\n");
		fprintf(htmlFile, "        const pointDistributionChart = echarts.init(document.getElementById('point-distribution-chart'));\n");
		fprintf(htmlFile, "        const accuracyChart = echarts.init(document.getElementById('accuracy-chart'));\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Function to calculate statistics for each problem\n");
		fprintf(htmlFile, "        function calculateProblemStatistics(contestData) {\n");
		fprintf(htmlFile, "            const stats = [];\n");
		fprintf(htmlFile, "            contestData.result.forEach(contest => {\n");
		fprintf(htmlFile, "                const problems = contest.problems;\n");
		fprintf(htmlFile, "                const results = contest.rows[0].problemResults;\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                problems.forEach((problem, index) => {\n");
		fprintf(htmlFile, "                    const maxPoints = problem.points;\n");
		fprintf(htmlFile, "                    const earnedPoints = results[index].points || 0;\n");
		fprintf(htmlFile, "                    const accuracy = ((earnedPoints / maxPoints) * 100).toFixed(2);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "                    stats.push({\n");
		fprintf(htmlFile, "                        contestName: contest.contest.name,\n");
		fprintf(htmlFile, "                        problemIndex: problem.index,\n");
		fprintf(htmlFile, "                        maxPoints: maxPoints,\n");
		fprintf(htmlFile, "                        earnedPoints: earnedPoints,\n");
		fprintf(htmlFile, "                        accuracy: parseFloat(accuracy)\n");
		fprintf(htmlFile, "                    });\n");
		fprintf(htmlFile, "                });\n");
		fprintf(htmlFile, "            });\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            return stats;\n");
		fprintf(htmlFile, "        }\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Calculate statistics\n");
		fprintf(htmlFile, "        const problemStats = calculateProblemStatistics(contestData);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Aggregate point distribution statistics\n");
		fprintf(htmlFile, "        const allPoints = problemStats.map(stat => stat.maxPoints);\n");
		fprintf(htmlFile, "        const minPoints = Math.min(...allPoints);\n");
		fprintf(htmlFile, "        const maxPoints = Math.max(...allPoints);\n");
		fprintf(htmlFile, "        const avgPoints = (allPoints.reduce((sum, val) => sum + val, 0) / allPoints.length).toFixed(2);\n");
		fprintf(htmlFile, "        const variance = (\n");
		fprintf(htmlFile, "            allPoints.reduce((sum, val) => sum + Math.pow(val - avgPoints, 2), 0) / allPoints.length\n");
		fprintf(htmlFile, "        ).toFixed(2);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Generate Point Distribution Chart Configuration\n");
		fprintf(htmlFile, "        const pointDistributionOption = {\n");
		fprintf(htmlFile, "            title: {\n");
		fprintf(htmlFile, "                text: 'Problem Point Distribution',\n");
		fprintf(htmlFile, "                left: 'center'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            tooltip: {\n");
		fprintf(htmlFile, "                trigger: 'axis'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            xAxis: {\n");
		fprintf(htmlFile, "                type: 'category',\n");
		fprintf(htmlFile, "                data: ['Min', 'Max', 'Average']\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            yAxis: {\n");
		fprintf(htmlFile, "                type: 'value'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            series: [\n");
		fprintf(htmlFile, "                {\n");
		fprintf(htmlFile, "                    name: 'Points',\n");
		fprintf(htmlFile, "                    type: 'bar',\n");
		fprintf(htmlFile, "                    data: [minPoints, maxPoints, parseFloat(avgPoints)]\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            ]\n");
		fprintf(htmlFile, "        };\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Generate Accuracy Chart Configuration\n");
		fprintf(htmlFile, "        const accuracyOption = {\n");
		fprintf(htmlFile, "            title: {\n");
		fprintf(htmlFile, "                text: 'Problem Accuracy Across Contests',\n");
		fprintf(htmlFile, "                left: 'center'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            tooltip: {\n");
		fprintf(htmlFile, "                trigger: 'axis'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            xAxis: {\n");
		fprintf(htmlFile, "                type: 'category',\n");
		fprintf(htmlFile, "                data: problemStats.map(stat => `${stat.contestName} - ${stat.problemIndex}`)\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            yAxis: {\n");
		fprintf(htmlFile, "                type: 'value'\n");
		fprintf(htmlFile, "            },\n");
		fprintf(htmlFile, "            series: [\n");
		fprintf(htmlFile, "                {\n");
		fprintf(htmlFile, "                    name: 'Accuracy (%%)',\n");
		fprintf(htmlFile, "                    type: 'line',\n");
		fprintf(htmlFile, "                    data: problemStats.map(stat => stat.accuracy),\n");
		fprintf(htmlFile, "                    markPoint: {\n");
		fprintf(htmlFile, "                        data: [\n");
		fprintf(htmlFile, "                            { type: 'max', name: 'Max Accuracy' },\n");
		fprintf(htmlFile, "                            { type: 'min', name: 'Min Accuracy' }\n");
		fprintf(htmlFile, "                        ]\n");
		fprintf(htmlFile, "                    }\n");
		fprintf(htmlFile, "                }\n");
		fprintf(htmlFile, "            ]\n");
		fprintf(htmlFile, "        };\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Populate Problem Statistics Table\n");
		fprintf(htmlFile, "        const tableBody = document.querySelector('#problem-statistics-table tbody');\n");
		fprintf(htmlFile, "        problemStats.forEach(stat => {\n");
		fprintf(htmlFile, "            const row = document.createElement('tr');\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const contestNameCell = document.createElement('td');\n");
		fprintf(htmlFile, "            contestNameCell.textContent = stat.contestName;\n");
		fprintf(htmlFile, "            row.appendChild(contestNameCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const problemIndexCell = document.createElement('td');\n");
		fprintf(htmlFile, "            problemIndexCell.textContent = stat.problemIndex;\n");
		fprintf(htmlFile, "            row.appendChild(problemIndexCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const maxPointsCell = document.createElement('td');\n");
		fprintf(htmlFile, "            maxPointsCell.textContent = stat.maxPoints;\n");
		fprintf(htmlFile, "            row.appendChild(maxPointsCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const avgPointsCell = document.createElement('td');\n");
		fprintf(htmlFile, "            avgPointsCell.textContent = stat.earnedPoints.toFixed(2);\n");
		fprintf(htmlFile, "            row.appendChild(avgPointsCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            const accuracyCell = document.createElement('td');\n");
		fprintf(htmlFile, "            accuracyCell.textContent = `${stat.accuracy}%%`;\n");
		fprintf(htmlFile, "            row.appendChild(accuracyCell);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "            tableBody.appendChild(row);\n");
		fprintf(htmlFile, "        });\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Set options to charts\n");
		fprintf(htmlFile, "        pointDistributionChart.setOption(pointDistributionOption);\n");
		fprintf(htmlFile, "        accuracyChart.setOption(accuracyOption);\n");
		fprintf(htmlFile, "\n");
		fprintf(htmlFile, "        // Display Variance in Separate Section\n");
		fprintf(htmlFile, "        document.getElementById('variance-value').textContent = variance;\n");
		fprintf(htmlFile, "        // Responsive layout\n");
		fprintf(htmlFile, "        window.addEventListener('resize', () => {\n");
		fprintf(htmlFile, "            pointDistributionChart.resize();\n");
		fprintf(htmlFile, "            accuracyChart.resize();\n");
		fprintf(htmlFile, "        });\n");
		fprintf(htmlFile, "    </script>\n");
		fprintf(htmlFile, "</body>\n");
		fprintf(htmlFile, "</html>\n");


	}




	free(str);
	fclose(htmlFile); // Close file
	open_file(filename);
}